from pathlib import Path


def test_release_directories_exist():
    expected = [
        "data/raw/reddit",
        "data/raw/xing",
        "data/raw/lfm",
        "data/raw/lfmalbum",
        "data/interim/reddit",
        "data/interim/xing",
        "data/interim/lfm",
        "data/interim/lfmalbum",
        "data/processed/reddit/train_test",
        "data/processed/xing",
        "data/processed/lfm/train_test",
        "data/processed/lfmalbum/train_test",
        "data/external/reddit",
        "data/external/xing",
        "data/external/lfm",
        "data/external/lfmalbum",
        "data/release_links",
        "checkpoints/reddit",
        "checkpoints/xing",
        "checkpoints/lfm",
        "checkpoints/lfmalbum",
        "checkpoints/pretrained",
        "outputs/reddit",
        "outputs/xing",
        "outputs/lfm",
        "outputs/lfmalbum",
        "outputs/demo",
        "logs/train",
        "logs/eval",
        "logs/infer",
        "logs/tensorboard",
        "runs/reddit",
        "runs/xing",
        "runs/lfm",
        "runs/lfmalbum",
        "experiments/reddit",
        "experiments/xing",
        "experiments/lfm",
        "experiments/lfmalbum",
        "experiments/ablation",
        "reports/figures",
        "reports/tables",
        "reports/metrics",
        "docs/assets",
        "tools/preprocessing",
    ]
    for value in expected:
        assert Path(value).is_dir(), value
